name: Build a Windows container

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v1

        - name: Build and push
          shell: bash
          run: |
            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username fpcojenkins --password-stdin
            IMAGE_ID=fpco/windows-docker-web:$GITHUB_SHA
            docker build -t $IMAGE_ID .
            docker push $IMAGE_ID
